import { randomUUID } from 'node:crypto';
import { ApiError } from '../common/errors.ts';
import { transactional } from '../database/transactions.ts';

export type CompanyRecord = { id: string; name: string; taxId?: string; status?: 'ACTIVE' | 'INACTIVE'; createdAt?: Date; updatedAt?: Date };
export type MembershipRecord = { id: string; userId: string; companyId: string; status?: 'ACTIVE' | 'INACTIVE'; startsAt?: Date; endsAt?: Date; roles?: string[] };
export type CompanyAudit = (event: Record<string, unknown>) => void | Promise<void>;
    type AuditEvent = Record<string, unknown> | ((result: any) => Record<string, unknown>);
export type CompanyRepository = {
  listActive(userId: string, now: Date): Promise<Array<{ membership: MembershipRecord; company: CompanyRecord }>>;
  list?(page: number, pageSize: number): Promise<{ items: CompanyRecord[]; total: number }>;
  create?(data: CompanyRecord, audit?: Record<string, unknown>): Promise<CompanyRecord>;
  update?(id: string, data: Partial<CompanyRecord>, audit?: AuditEvent): Promise<CompanyRecord | undefined>;
  listMemberships?(page: number, pageSize: number): Promise<{ items: MembershipRecord[]; total: number }>;
  establishMembership?(data: MembershipRecord, audit?: Record<string, unknown>): Promise<MembershipRecord>;
  deactivateMembership?(id: string, endsAt: Date, audit?: AuditEvent): Promise<MembershipRecord | undefined>;
};

type AuditDelegate = { create(args: { data: Record<string, unknown> }): Promise<unknown> };
type PrismaClientLike = { company: any; membership: any; auditEvent?: AuditDelegate; $transaction?: (fn: (tx: any) => Promise<unknown>) => Promise<unknown> };

function companyOf(value: any): CompanyRecord { return { id: String(value.id), name: String(value.name), taxId: value.taxId ?? undefined, status: value.status, createdAt: value.createdAt, updatedAt: value.updatedAt }; }
function membershipOf(value: any): MembershipRecord { return { id: String(value.id), userId: String(value.userId), companyId: String(value.companyId), status: value.status, startsAt: value.startsAt, endsAt: value.endsAt }; }
function auditData(event: Record<string, unknown>) { return { userId: event.userId, companyId: event.companyId, resource: event.resource, action: event.action, recordId: event.recordId, result: event.result, detail: event.detail }; }

export class InMemoryCompanyRepository implements CompanyRepository {
  private readonly companies: CompanyRecord[]; private readonly memberships: MembershipRecord[];
  constructor(companies: CompanyRecord[] = [], memberships: MembershipRecord[] = []) { this.companies = companies; this.memberships = memberships; }
  async listActive(userId: string, now: Date) { return this.memberships.filter(m => m.userId === userId && active(m, now)).map(m => ({ membership: m, company: this.companies.find(c => c.id === m.companyId) })).filter((e): e is { membership: MembershipRecord; company: CompanyRecord } => Boolean(e.company && active(e.company, now))); }
  async list(page: number, pageSize: number) { return { items: this.companies.slice((page - 1) * pageSize, page * pageSize), total: this.companies.length }; }
  async create(data: CompanyRecord) { this.companies.push(data); return data; }
  async update(id: string, data: Partial<CompanyRecord>) { const item = this.companies.find(c => c.id === id); if (!item) return undefined; Object.assign(item, data); return item; }
  async listMemberships(page: number, pageSize: number) { return { items: this.memberships.slice((page - 1) * pageSize, page * pageSize), total: this.memberships.length }; }
  async establishMembership(data: MembershipRecord) { this.memberships.push(data); return data; }
  async deactivateMembership(id: string, endsAt: Date) { const item = this.memberships.find(m => m.id === id); if (!item) return undefined; item.status = 'INACTIVE'; item.endsAt = endsAt; return item; }
}

/** Prisma adapter. Mutations use an interactive transaction so the audit insert commits atomically. */
export class PrismaCompanyRepository implements CompanyRepository {
  private readonly client: PrismaClientLike; private readonly company: any; private readonly membership: any; private readonly audit?: AuditDelegate;
  constructor(clientOrMembership: PrismaClientLike | any, membership?: any, audit?: AuditDelegate) {
    if (clientOrMembership?.company && clientOrMembership?.membership) { this.client = clientOrMembership; this.company = clientOrMembership.company; this.membership = clientOrMembership.membership; this.audit = clientOrMembership.auditEvent ?? audit; }
    else { this.client = { membership: clientOrMembership }; this.company = undefined; this.membership = clientOrMembership; this.audit = audit; }
  }
  async listActive(userId: string, now: Date) {
    const rows = await this.membership.findMany({ where: { userId, status: 'ACTIVE', startsAt: { lte: now }, OR: [{ endsAt: null }, { endsAt: { gt: now } }], company: { status: 'ACTIVE' } }, include: { company: true } });
    return rows.map((row: any) => ({ membership: membershipOf(row), company: companyOf(row.company) }));
  }
  async list(page: number, pageSize: number) { const [items, total] = await Promise.all([this.company.findMany({ skip: (page - 1) * pageSize, take: pageSize, orderBy: { createdAt: 'desc' } }), this.company.count()]); return { items: items.map(companyOf), total }; }
  async listMemberships(page: number, pageSize: number) { const [items, total] = await Promise.all([this.membership.findMany({ skip: (page - 1) * pageSize, take: pageSize, orderBy: { startsAt: 'desc' }, include: { roles: { include: { role: { select: { name: true, status: true } } } } } }), this.membership.count()]); return { items: items.map((row: any) => ({ ...membershipOf(row), roles: (row.roles ?? []).filter((link: any) => link.role?.status !== 'INACTIVE').map((link: any) => String(link.role.name)) })), total }; }
  async create(data: CompanyRecord, audit?: Record<string, unknown>) { return this.mutate(async (tx: any) => { if (tx.company.findFirst) { const existing = await tx.company.findFirst({ where: { OR: [{ name: data.name }, ...(data.taxId ? [{ taxId: data.taxId }] : [])] }, select: { id: true } }); if (existing) { const error = Object.assign(new Error('duplicate company'), { code: 'P2002' }); throw error; } } return companyOf(await tx.company.create({ data: { id: data.id, name: data.name, taxId: data.taxId, status: data.status } })); }, audit); }
  async update(id: string, data: Partial<CompanyRecord>, audit?: AuditEvent) { return this.mutate(async (tx: any) => { const found = await tx.company.findUnique({ where: { id } }); if (!found) return undefined; return companyOf(await tx.company.update({ where: { id }, data })); }, audit); }
  async establishMembership(data: MembershipRecord, audit?: Record<string, unknown>) { return this.mutate(async (tx: any) => membershipOf(await tx.membership.create({ data: { id: data.id, userId: data.userId, companyId: data.companyId, status: data.status, startsAt: data.startsAt, endsAt: data.endsAt } })), audit); }
  async deactivateMembership(id: string, endsAt: Date, audit?: AuditEvent) { return this.mutate(async (tx: any) => { const found = await tx.membership.findUnique({ where: { id } }); if (!found) return undefined; return membershipOf(await tx.membership.update({ where: { id }, data: { status: 'INACTIVE', endsAt } })); }, audit); }
  private async mutate<T>(mutation: (tx: any) => Promise<T>, event?: AuditEvent): Promise<T> { const work = async (tx: any) => { const result = await mutation(tx); const eventData = result === undefined ? undefined : typeof event === 'function' ? event(result) : event; if (eventData && this.audit) await tx.auditEvent.create({ data: auditData(eventData) }); return result; }; return this.client.$transaction ? transactional(this.client as any, work) : work(this.client); }
}

function active(v: { status?: string; startsAt?: Date; endsAt?: Date }, now: Date) { return v.status !== 'INACTIVE' && (!v.startsAt || v.startsAt <= now) && (!v.endsAt || v.endsAt > now); }
function required(v: unknown, field: string) { if (typeof v !== 'string' || !v.trim()) throw new ApiError(400, 'VALIDATION_ERROR', `${field} is required.`); return v.trim(); }
function page(input: Record<string, unknown>) { const number = Number.isInteger(input.page) && Number(input.page) > 0 ? Number(input.page) : 1; const size = Number.isInteger(input.pageSize) && Number(input.pageSize) > 0 && Number(input.pageSize) <= 100 ? Number(input.pageSize) : 20; return { page: number, pageSize: size }; }
function unknown(body: Record<string, unknown>, allowed: string[]) { const keys = Object.keys(body).filter(k => !allowed.includes(k)); if (keys.length) throw new ApiError(400, 'VALIDATION_ERROR', `Unknown fields: ${keys.join(', ')}.`); }
function duplicate(error: unknown): never { if ((error as any)?.code === 'P2002') throw new ApiError(409, 'DUPLICATE_RESOURCE', 'The requested resource already exists.'); throw error; }

export class CompaniesService {
  readonly companies: CompanyRecord[]; readonly memberships: MembershipRecord[]; private readonly audit?: CompanyAudit; private readonly repository: CompanyRepository;
  constructor(companies: CompanyRecord[] = [], memberships: MembershipRecord[] = [], audit?: CompanyAudit, repository?: CompanyRepository) { this.companies = companies; this.memberships = memberships; this.audit = audit; this.repository = repository ?? new InMemoryCompanyRepository(companies, memberships); }
  async listActive(userId: string, now = new Date()) { const entries = await this.repository.listActive(userId, now); return entries.filter(e => active(e.membership, now) && active(e.company, now)).sort((a, b) => a.company.name.localeCompare(b.company.name) || a.company.id.localeCompare(b.company.id)).map(({ company, membership }) => ({ id: company.id, name: company.name, membershipId: membership.id })); }
  async select(userId: string, companyId: unknown, now = new Date()) { const id = required(companyId, 'companyId'); const item = (await this.listActive(userId, now)).find(c => c.id === id); if (!item) throw new ApiError(403, 'COMPANY_CONTEXT_INVALID', 'The company context is not available.'); await this.audit?.({ userId, companyId: id, resource: 'company-context', action: 'select', recordId: id, result: 'SUCCESS' }); return item; }
  async context(userId: string, companyId: string, now = new Date()) { const item = (await this.listActive(userId, now)).find(c => c.id === companyId); if (!item) throw new ApiError(403, 'COMPANY_CONTEXT_INVALID', 'The company context could not be verified.'); return item; }
  async list(query: Record<string, unknown> = {}) { const p = page(query); if (this.repository.list) { const result = await this.repository.list(p.page, p.pageSize); return { items: result.items, ...p, total: result.total }; } const items = this.companies.slice((p.page - 1) * p.pageSize, p.page * p.pageSize); return { items, ...p, total: this.companies.length }; }
  async update(id: unknown, body: Record<string, unknown>, actorId?: string) { const companyId = required(id, 'id'); unknown(body, ['status']); if (body.status !== 'ACTIVE' && body.status !== 'INACTIVE') throw new ApiError(400, 'VALIDATION_ERROR', 'status is invalid.'); const current = (await this.list({ page: 1, pageSize: 100 })).items.find(c => c.id === companyId); if (!current) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Company was not found.'); const next = body.status as 'ACTIVE' | 'INACTIVE'; const event = { userId: actorId, resource: 'company', action: 'update', recordId: companyId, result: 'SUCCESS', detail: { before: { status: current.status }, after: { status: next } } }; const result = this.repository.update ? await this.repository.update(companyId, { status: next }, event) : Object.assign(current, { status: next }); await this.audit?.(event); return result; }
  async create(body: Record<string, unknown>, actorId?: string) { unknown(body, ['name', 'taxId']); const name = required(body.name, 'name'); const taxId = body.taxId === undefined ? undefined : required(body.taxId, 'taxId'); if (this.companies.some(c => c.name.toLowerCase() === name.toLowerCase() || (taxId && c.taxId === taxId))) throw new ApiError(409, 'DUPLICATE_RESOURCE', 'A company with this identity already exists.'); const company = { id: randomUUID(), name, taxId, status: 'ACTIVE' as const }; try { const result = this.repository.create ? await this.repository.create(company, { userId: actorId, resource: 'company', action: 'create', recordId: company.id, result: 'SUCCESS' }) : company; if (!this.repository.create) this.companies.push(company); await this.audit?.({ userId: actorId, resource: 'company', action: 'create', recordId: company.id, result: 'SUCCESS' }); return result; } catch (error) { return duplicate(error); } }
  async establishMembership(body: Record<string, unknown>, actorId?: string) { unknown(body, ['userId', 'companyId', 'startsAt', 'endsAt']); const userId = required(body.userId, 'userId'); const companyId = required(body.companyId, 'companyId'); if (!this.companies.some(c => c.id === companyId) && this.repository.list) { const company = await this.repository.list(1, 100); if (!company.items.some(c => c.id === companyId)) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Company was not found.'); } else if (!this.companies.some(c => c.id === companyId)) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Company was not found.'); const startsAt = body.startsAt ? new Date(String(body.startsAt)) : new Date(); const endsAt = body.endsAt ? new Date(String(body.endsAt)) : undefined; if (Number.isNaN(startsAt.getTime()) || (endsAt && Number.isNaN(endsAt.getTime()))) throw new ApiError(400, 'VALIDATION_ERROR', 'Membership dates are invalid.'); if (this.memberships.some(m => m.userId === userId && m.companyId === companyId)) throw new ApiError(409, 'DUPLICATE_RESOURCE', 'Membership already exists.'); const membership = { id: randomUUID(), userId, companyId, status: 'ACTIVE' as const, startsAt, endsAt }; try { const result = this.repository.establishMembership ? await this.repository.establishMembership(membership, { userId: actorId, companyId, resource: 'membership', action: 'establish', recordId: membership.id, result: 'SUCCESS' }) : membership; if (!this.repository.establishMembership) this.memberships.push(membership); await this.audit?.({ userId: actorId, companyId, resource: 'membership', action: 'establish', recordId: membership.id, result: 'SUCCESS' }); return result; } catch (error) { return duplicate(error); } }
  async listMemberships(query: Record<string, unknown> = {}) { const p = page(query); if (this.repository.listMemberships) { const result = await this.repository.listMemberships(p.page, p.pageSize); return { items: result.items, ...p, total: result.total }; } const items = this.memberships.slice((p.page - 1) * p.pageSize, p.page * p.pageSize); return { items, ...p, total: this.memberships.length }; }
  async deactivateMembership(id: unknown, actorId?: string) { const membershipId = required(id, 'id'); const endsAt = new Date(); let membership: MembershipRecord | undefined; if (this.repository.deactivateMembership) membership = await this.repository.deactivateMembership(membershipId, endsAt, (result) => ({ userId: actorId, companyId: result.companyId, resource: 'membership', action: 'deactivate', recordId: membershipId, result: 'SUCCESS' })); else { membership = this.memberships.find(m => m.id === membershipId); if (membership) { membership.status = 'INACTIVE'; membership.endsAt = endsAt; } } if (!membership) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Membership was not found.'); await this.audit?.({ userId: actorId, companyId: membership.companyId, resource: 'membership', action: 'deactivate', recordId: membership.id, result: 'SUCCESS' }); return membership; }
}
export function isActiveMembership(membership: MembershipRecord, now = new Date()) { return active(membership, now); }
