import { randomUUID } from 'node:crypto';
import { ApiError } from '../common/errors.ts';
import { transactional } from '../database/transactions.ts';

export type PermissionRecord = { id: string; code: string; resource: string; action: string; description?: string; status?: 'ACTIVE' | 'INACTIVE' };
export type PermissionRepository = { list(): Promise<PermissionRecord[]>; create(data: PermissionRecord, audit?: Record<string, unknown>): Promise<PermissionRecord>; update?(id: string, data: Partial<PermissionRecord>, audit?: Record<string, unknown>): Promise<PermissionRecord | undefined> };
const required = (v: unknown, field: string) => { if (typeof v !== 'string' || !v.trim()) throw new ApiError(400, 'VALIDATION_ERROR', `${field} is required.`); return v.trim(); };
const unknown = (body: Record<string, unknown>, allowed: string[]) => { const keys = Object.keys(body).filter(k => !allowed.includes(k)); if (keys.length) throw new ApiError(400, 'VALIDATION_ERROR', `Unknown fields: ${keys.join(', ')}.`); };
export class InMemoryPermissionRepository implements PermissionRepository { readonly permissions: PermissionRecord[]; constructor(permissions: PermissionRecord[] = []) { this.permissions = permissions; } async list() { return [...this.permissions]; } async create(data: PermissionRecord) { this.permissions.push(data); return data; } async update(id: string, data: Partial<PermissionRecord>) { const item = this.permissions.find(p => p.id === id); if (!item) return undefined; Object.assign(item, data); return item; } }
export class PrismaPermissionRepository implements PermissionRepository {
  private readonly client: { permission: any; $transaction?: (fn: (tx: any) => Promise<unknown>) => Promise<unknown> };
  constructor(client: { permission: any; $transaction?: (fn: (tx: any) => Promise<unknown>) => Promise<unknown> }) { this.client = client; }
  async list() { return this.client.permission.findMany({ orderBy: [{ resource: 'asc' }, { action: 'asc' }, { code: 'asc' }] }); }
  async create(data: PermissionRecord, audit?: Record<string, unknown>) { const work = async (tx: any) => { const result = await tx.permission.create({ data }); if (audit && tx.auditEvent) await tx.auditEvent.create({ data: audit }); return result; }; return this.client.$transaction ? transactional(this.client as any, work) : work(this.client); }
  async update(id: string, data: Partial<PermissionRecord>, audit?: Record<string, unknown>) { const work = async (tx: any) => { const result = await tx.permission.update({ where: { id }, data }); if (audit && tx.auditEvent) await tx.auditEvent.create({ data: audit }); return result; }; return this.client.$transaction ? transactional(this.client as any, work) : work(this.client); }
}
export class PermissionsService {
  private readonly repository: PermissionRepository; private readonly audit?: (event: Record<string, unknown>) => void | Promise<void>;
  constructor(repository: PermissionRepository = new InMemoryPermissionRepository(), audit?: (event: Record<string, unknown>) => void | Promise<void>) { this.repository = repository; this.audit = audit; }
  list() { return this.repository.list(); }
  async update(id: unknown, body: Record<string, unknown>, actorId?: string) { const permissionId = required(id, 'id'); unknown(body, ['status']); if (body.status !== 'ACTIVE' && body.status !== 'INACTIVE') throw new ApiError(400, 'VALIDATION_ERROR', 'status is invalid.'); const current = (await this.list()).find(permission => permission.id === permissionId); if (!current) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Permission was not found.'); const event = { userId: actorId, resource: 'permission', action: 'update', recordId: permissionId, result: 'SUCCESS', detail: { before: { status: current.status }, after: { status: body.status } } }; const result = this.repository.update ? await this.repository.update(permissionId, { status: body.status as 'ACTIVE' | 'INACTIVE' }, event) : { ...current, status: body.status as 'ACTIVE' | 'INACTIVE' }; await this.audit?.(event); return result; }
  async create(body: Record<string, unknown>, actorId?: string) { unknown(body, ['code', 'resource', 'action', 'description']); const permission: PermissionRecord = { id: randomUUID(), code: required(body.code, 'code'), resource: required(body.resource, 'resource'), action: required(body.action, 'action'), description: body.description == null ? undefined : String(body.description), status: 'ACTIVE' }; try { const result = await this.repository.create(permission, { userId: actorId, resource: 'permission', action: 'create', recordId: permission.id, result: 'SUCCESS', detail: { permission: permission.code } }); await this.audit?.({ userId: actorId, resource: 'permission', action: 'create', recordId: permission.id, result: 'SUCCESS', detail: { permission: permission.code } }); return result; } catch (e) { if ((e as any)?.code === 'P2002') throw new ApiError(409, 'DUPLICATE_RESOURCE', 'The permission already exists.'); throw e; } }
}
