import { randomUUID } from 'node:crypto';
import { ApiError } from '../common/errors.ts';
import { transactional } from '../database/transactions.ts';

export type RoleScope = 'PLATFORM' | 'SHARED' | 'COMPANY';
export type RoleRecord = { id: string; name: string; description?: string; scope: RoleScope; companyId?: string | null; status?: 'ACTIVE' | 'INACTIVE'; companyIds?: string[]; permissions?: string[] };
export type RoleRepository = {
  list?(companyId?: string): Promise<RoleRecord[]>;
  create(data: RoleRecord, audit?: Record<string, unknown>): Promise<RoleRecord>;
  update(id: string, data: Partial<RoleRecord>, audit?: Record<string, unknown>): Promise<RoleRecord | undefined>;
  setPermission(roleId: string, permissionId: string, add: boolean, audit?: Record<string, unknown>): Promise<unknown>;
  assign(roleId: string, membershipId: string, companyId: string, audit?: Record<string, unknown>): Promise<unknown>;
  removeAssignment(roleId: string, membershipId: string, audit?: Record<string, unknown>): Promise<unknown>;
  assignPlatform?(roleId: string, userId: string, audit?: Record<string, unknown>): Promise<unknown>;
  listCompanies?(roleId: string): Promise<string[]>;
  setCompanies?(roleId: string, companyIds: string[], audit?: Record<string, unknown>): Promise<string[]>;
};

type Client = { role: any; rolePermission: any; membershipRole: any; roleCompany?: any; membership?: any; permission?: any; auditEvent?: any; $transaction?: (fn: (tx: any) => Promise<unknown>) => Promise<unknown> };
const required = (v: unknown, field: string) => { if (typeof v !== 'string' || !v.trim()) throw new ApiError(400, 'VALIDATION_ERROR', `${field} is required.`); return v.trim(); };
const unknown = (body: Record<string, unknown>, allowed: string[]) => { const keys = Object.keys(body).filter(k => !allowed.includes(k)); if (keys.length) throw new ApiError(400, 'VALIDATION_ERROR', `Unknown fields: ${keys.join(', ')}.`); };
function scope(v: unknown): RoleScope { if (v !== 'PLATFORM' && v !== 'SHARED' && v !== 'COMPANY') throw new ApiError(400, 'VALIDATION_ERROR', 'scope is invalid.'); return v; }

export class InMemoryRoleRepository implements RoleRepository {
  readonly roles: RoleRecord[]; readonly links: Array<{ roleId: string; permissionId: string }>; readonly assignments: Array<{ roleId: string; membershipId: string; companyId: string }>;
  readonly eligibility: Array<{ roleId: string; companyId: string }>;
  constructor(roles: RoleRecord[] = [], links: Array<{ roleId: string; permissionId: string }> = [], assignments: Array<{ roleId: string; membershipId: string; companyId: string }> = [], eligibility: Array<{ roleId: string; companyId: string }> = []) { this.roles = roles; this.links = links; this.assignments = assignments; this.eligibility = eligibility; }
  async list(companyId?: string) { return this.roles.filter(r => !companyId || r.companyId === companyId || r.scope === 'SHARED').map(r => ({ ...r, companyIds: this.eligibility.filter(e => e.roleId === r.id).map(e => e.companyId) })); }
  async create(data: RoleRecord) { this.roles.push(data); for (const companyId of data.companyIds ?? []) this.eligibility.push({ roleId: data.id, companyId }); return data; }
  async listCompanies(roleId: string) { return this.eligibility.filter(e => e.roleId === roleId).map(e => e.companyId); }
  async setCompanies(roleId: string, companyIds: string[]) { for (let i = this.eligibility.length - 1; i >= 0; i--) if (this.eligibility[i].roleId === roleId) this.eligibility.splice(i, 1); for (const companyId of companyIds) this.eligibility.push({ roleId, companyId }); return [...companyIds]; }
  async update(id: string, data: Partial<RoleRecord>) { const role = this.roles.find(r => r.id === id); if (!role) return undefined; Object.assign(role, data); return role; }
  async setPermission(roleId: string, permissionId: string, add: boolean) { const i = this.links.findIndex(x => x.roleId === roleId && x.permissionId === permissionId); if (add && i >= 0) throw new ApiError(409, 'DUPLICATE_RESOURCE', 'Permission is already assigned to this role.'); if (add) this.links.push({ roleId, permissionId }); if (!add && i >= 0) this.links.splice(i, 1); return { roleId, permissionId, added: add }; }
  async assign(roleId: string, membershipId: string, companyId: string) { if (this.assignments.some(x => x.roleId === roleId && x.membershipId === membershipId)) throw new ApiError(409, 'DUPLICATE_RESOURCE', 'Role is already assigned to this membership.'); this.assignments.push({ roleId, membershipId, companyId }); return { roleId, membershipId, companyId }; }
  async removeAssignment(roleId: string, membershipId: string) { const i = this.assignments.findIndex(x => x.roleId === roleId && x.membershipId === membershipId); if (i >= 0) return this.assignments.splice(i, 1)[0]; return undefined; }
  async assignPlatform(roleId: string, userId: string) { return { roleId, userId }; }
}

export class PrismaRoleRepository implements RoleRepository {
  private readonly client: Client;
  constructor(client: Client) { this.client = client; }
  async list(companyId?: string) { const rows = await this.client.role.findMany({ where: companyId ? { OR: [{ companyId }, { scope: 'SHARED' }] } : {}, include: { ...(this.client.roleCompany ? { companies: true } : {}), permissions: { include: { permission: true } } }, orderBy: [{ name: 'asc' }, { id: 'asc' }] }); return rows.map((row: any) => ({ ...row, companyIds: (row.companies ?? []).map((entry: any) => String(entry.companyId)), permissions: (row.permissions ?? []).filter((entry: any) => entry.permission?.status !== 'INACTIVE').map((entry: any) => String(entry.permission.code)) })) as RoleRecord[]; }
  async create(data: RoleRecord, audit?: Record<string, unknown>) { return this.mutate(async tx => { const role = await tx.role.create({ data: { id: data.id, name: data.name, description: data.description, scope: data.scope, companyId: data.companyId, status: data.status } }); if (tx.roleCompany) for (const companyId of data.companyIds ?? []) await tx.roleCompany.create({ data: { roleId: data.id, companyId } }); return role; }, audit); }
  async listCompanies(roleId: string) { if (!this.client.roleCompany) return []; return (await this.client.roleCompany.findMany({ where: { roleId } })).map((entry: any) => String(entry.companyId)); }
  async setCompanies(roleId: string, companyIds: string[], audit?: Record<string, unknown>) { if (!this.client.roleCompany) throw new Error('REPOSITORY_OPERATION_UNAVAILABLE'); return this.mutate(async tx => { await tx.roleCompany.deleteMany({ where: { roleId } }); for (const companyId of companyIds) await tx.roleCompany.create({ data: { roleId, companyId } }); return companyIds; }, audit); }
  async update(id: string, data: Partial<RoleRecord>, audit?: Record<string, unknown>) { return this.mutate(async tx => { const found = await tx.role.findUnique({ where: { id } }); if (!found) return undefined; return tx.role.update({ where: { id }, data }); }, audit); }
  async setPermission(roleId: string, permissionId: string, add: boolean, audit?: Record<string, unknown>) { return this.mutate(async tx => add ? tx.rolePermission.create({ data: { roleId, permissionId } }) : tx.rolePermission.delete({ where: { roleId_permissionId: { roleId, permissionId } } }), audit); }
  async assign(roleId: string, membershipId: string, companyId: string, audit?: Record<string, unknown>) { return this.mutate(async tx => tx.membershipRole.create({ data: { roleId, membershipId, companyId } }), audit); }
  async removeAssignment(roleId: string, membershipId: string, audit?: Record<string, unknown>) { return this.mutate(async tx => tx.membershipRole.delete({ where: { membershipId_roleId: { membershipId, roleId } } }), audit); }
  async assignPlatform(roleId: string, userId: string, audit?: Record<string, unknown>) { return this.mutate(async tx => tx.platformRoleAssignment.create({ data: { roleId, userId } }), audit); }
  private async mutate<T>(work: (tx: any) => Promise<T>, event?: Record<string, unknown>) { return this.client.$transaction ? transactional(this.client as any, async tx => { const result = await work(tx); if (event && tx.auditEvent) await tx.auditEvent.create({ data: event }); return result; }) : work(this.client); }
}

export class RolesService {
  private readonly repository: RoleRepository; private readonly audit?: (event: Record<string, unknown>) => void | Promise<void>;
  constructor(repository: RoleRepository = new InMemoryRoleRepository(), audit?: (event: Record<string, unknown>) => void | Promise<void>) { this.repository = repository; this.audit = audit; }
  async list(companyId?: string) { return this.repository.list ? this.repository.list(companyId) : []; }
  async update(id: unknown, body: Record<string, unknown>, actorId?: string) { const roleId = required(id, 'id'); unknown(body, ['status']); if (body.status !== 'ACTIVE' && body.status !== 'INACTIVE') throw new ApiError(400, 'VALIDATION_ERROR', 'status is invalid.'); const current = (await this.list()).find(role => role.id === roleId); if (!current) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Role was not found.'); const event = { userId: actorId, companyId: current.companyId ?? undefined, resource: 'role', action: 'update', recordId: roleId, result: 'SUCCESS', detail: { before: { status: current.status }, after: { status: body.status } } }; const result = this.repository.update ? await this.repository.update(roleId, { status: body.status as 'ACTIVE' | 'INACTIVE' }, event) : undefined; await this.audit?.(event); return result ?? { ...current, status: body.status as 'ACTIVE' | 'INACTIVE' }; }
  async create(body: Record<string, unknown>, actorId?: string) { unknown(body, ['name', 'description', 'scope', 'companyId', 'companyIds']); const roleScope = scope(body.scope ?? 'COMPANY'); const companyId = body.companyId == null ? undefined : required(body.companyId, 'companyId'); if (roleScope === 'COMPANY' && !companyId) throw new ApiError(400, 'VALIDATION_ERROR', 'companyId is required for company roles.'); if (roleScope !== 'COMPANY' && companyId) throw new ApiError(400, 'INVALID_SCOPE', 'Only company roles may have a companyId.'); const rawCompanyIds = Array.isArray(body.companyIds) ? body.companyIds.map(v => required(v, 'companyIds[]')) : []; if (rawCompanyIds.length && roleScope !== 'SHARED') throw new ApiError(400, 'INVALID_SCOPE', 'Only shared roles may enable specific companies.'); const companyIds = roleScope === 'SHARED' ? rawCompanyIds : []; const role: RoleRecord = { id: randomUUID(), name: required(body.name, 'name'), description: body.description == null ? undefined : String(body.description), scope: roleScope, companyId, status: 'ACTIVE', companyIds }; try { const result = await this.repository.create(role, { userId: actorId, companyId, resource: 'role', action: 'create', recordId: role.id, result: 'SUCCESS' }); await this.audit?.({ userId: actorId, companyId, resource: 'role', action: 'create', recordId: role.id, result: 'SUCCESS' }); return result; } catch (e) { if ((e as any)?.code === 'P2002') throw new ApiError(409, 'DUPLICATE_RESOURCE', 'The role already exists.'); throw e; } }
  async permission(roleId: unknown, body: Record<string, unknown>, actorId?: string, add = true) { const id = required(roleId, 'id'); unknown(body, ['permissionId', 'code']); const permissionId = required(body.permissionId ?? body.code, 'permissionId'); const result = await this.repository.setPermission(id, permissionId, add, { userId: actorId, resource: 'role-permission', action: add ? 'add' : 'remove', recordId: id, result: 'SUCCESS', detail: { permission: permissionId } }); await this.audit?.({ userId: actorId, resource: 'role-permission', action: add ? 'add' : 'remove', recordId: id, result: 'SUCCESS', detail: { permission: permissionId } }); return result; }
  async assign(roleId: unknown, body: Record<string, unknown>, actorId?: string) { const id = required(roleId, 'id'); unknown(body, ['membershipId', 'companyId']); const membershipId = required(body.membershipId, 'membershipId'); const companyId = required(body.companyId, 'companyId'); const role = (await this.list()).find(x => x.id === id); if (!role) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Role was not found in this company.'); if (role.scope === 'PLATFORM') throw new ApiError(400, 'INVALID_SCOPE', 'Platform roles cannot be assigned to memberships.'); if (role.scope === 'COMPANY' && role.companyId !== companyId) throw new ApiError(400, 'INVALID_SCOPE', 'Role and membership company must match.'); const eligible = role.scope === 'SHARED' ? (role.companyIds ?? await this.repository.listCompanies?.(role.id) ?? []) : []; if (role.scope === 'SHARED' && eligible.length && !eligible.includes(companyId)) throw new ApiError(400, 'INVALID_SCOPE', 'The role is not enabled for this company.'); const result = await this.repository.assign(id, membershipId, companyId, { userId: actorId, companyId, resource: 'membership-role', action: 'assign', recordId: id, result: 'SUCCESS' }); await this.audit?.({ userId: actorId, companyId, resource: 'membership-role', action: 'assign', recordId: id, result: 'SUCCESS' }); return result; }
  async setCompanies(roleId: unknown, body: Record<string, unknown>, actorId?: string) {
    const id = required(roleId, 'id'); unknown(body, ['companyIds']);
    if (body.companyIds !== undefined && !Array.isArray(body.companyIds)) throw new ApiError(400, 'VALIDATION_ERROR', 'companyIds must be an array.');
    const companyIds = Array.isArray(body.companyIds) ? [...new Set(body.companyIds.map(v => required(v, 'companyIds[]')))] : [];
    const role = (await this.list()).find(x => x.id === id); if (!role) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Role was not found.');
    if (role.scope !== 'SHARED') throw new ApiError(400, 'INVALID_SCOPE', 'Only shared roles may enable specific companies.');
    if (!this.repository.setCompanies) throw new ApiError(503, 'CONTEXT_UNAVAILABLE', 'Role company eligibility is unavailable.');
    const before = await this.repository.listCompanies?.(id) ?? [];
    const event = { userId: actorId, resource: 'role-company', action: 'set', recordId: id, result: 'SUCCESS', detail: { before: { companyIds: before }, after: { companyIds } } };
    const result = await this.repository.setCompanies(id, companyIds, event); await this.audit?.(event); return { roleId: id, companyIds: result };
  }
  async assignPlatform(roleId: unknown, body: Record<string, unknown>, actorId?: string) { const id = required(roleId, 'id'); const userId = required(body.userId, 'userId'); const role = (await this.list()).find(x => x.id === id); if (!role || role.scope !== 'PLATFORM') throw new ApiError(400, 'INVALID_SCOPE', 'Only platform roles may use platform assignments.'); if (!this.repository.assignPlatform) throw new ApiError(503, 'CONTEXT_UNAVAILABLE', 'Platform role assignment is unavailable.'); return this.repository.assignPlatform(id, userId, { userId: actorId, resource: 'platform-role-assignment', action: 'assign', recordId: id, result: 'SUCCESS' }); }
  async unassign(roleId: unknown, membershipId: unknown, actorId?: string) { const result = await this.repository.removeAssignment(required(roleId, 'id'), required(membershipId, 'membershipId'), { userId: actorId, resource: 'membership-role', action: 'remove', recordId: String(roleId), result: 'SUCCESS' }); await this.audit?.({ userId: actorId, resource: 'membership-role', action: 'remove', recordId: String(roleId), result: 'SUCCESS' }); return result; }
}
